Implement File Expiration
sbu-416-24sp/orcanet-market-rust pull request #1
Opened 2024-03-09 19:20 UTC by andrewctam

Files are lazily removed on a call to CheckHolders. When a client calls CheckHolders, files that are expired are removed from the vector and will not be returned. Also committed files that was not brought in during init.

2024-03-09 22:24 UTC, xiej2520 commented
Code compiles and runs correctly for me.
We could use binary search for the holder times, but we should enforce the sorted holders Vec somehow.

2024-03-11 22:14 UTC, reaovyd requested changes
Thanks for your work on this! 

# Misc
Just have a few more comments on things I can't directly comment on in the files.

## Directory Structure
Just for another suggestion for directory structure that I can't currently comment on. 

1. The `market_test.rs` can be moved to the special `tests/` folder on the same directory level as the `src/` directory since that will be where integration tests are (and it seems the tests are integration tests).
2. `main.rs` can probably be moved to `bin/server.rs`
3. `bin/` folder is essentially where your application source code that compiles into binaries should be placed not where your integration tests go.
4. Doing the above would involve changing the `default-run` in `Cargo.toml` to `default-run = "server"`.
5. When you move the integration tests to `tests/`, remove the unnecessary `main` function in that file and the `#[cfg](test); mod tests{}` in there. For example, something [this](https://gist.github.com/reaovyd/a0ed2995b06890292d0cef95e2351588).

My suggested directory structure:
![image](https://github.com/sbu-416-24sp/orcanet-market-rust/assets/65320857/c441734f-4e86-4750-93b3-04a77e0db3c4)

### Proto and cargo workspace
I think you can also roll with a cargo workspace and separate the `proto` stuff in another workspace crate so you don't have to continuously do this

```Rust
pub mod market {
    tonic::include_proto!("market"); // Path to proto file
}
```
which would increase codegen time (I think?). You can probably just `include_proto` in a specific `proto` crate and just import crates as usual with the `use` keyword for a specific `market_proto` crate you make in the workspace.

## Price per chunk
On another note, just a question, but what if the same peer wants to have a specific price per chunk for **any** file? Seems like the price per chunk for each file they upload at the moment is tightly coupled with the peer itself.

2024-03-11 22:14 UTC, reaovyd commented on src/lib.rs
> +    since_the_epoch.as_secs() as u64
Nitpick (non blocking): `as_secs`'s return type is already `u64` so there is no point in converting it with `as u64` again.

2024-03-11 22:14 UTC, reaovyd commented on src/main.rs
>              user: req.user.ok_or(())?,
Suggestion (non-blocking): You're probably looking for a `try_from` trait implementation so you don't have to implement your own method like that. Something like this

```Rust
impl TryFrom<RegisterFileRequest> for FileRequest {
    type Error = ();

    fn try_from(req: RegisterFileRequest) -> Result<Self, Self::Error> {
        Ok(Self {
            user: req.user.ok_or(())?,
            file_hash: req.file_hash,
            expiration: get_current_time() + EXPIRATION_OFFSET,
        })
    }
}
```

2024-03-11 22:14 UTC, reaovyd commented on src/main.rs
>  impl FileRequest {
Nitpicking (non blocking): For the `Error` type, you can look into making a custom error type with [`thiserror`](https://docs.rs/thiserror/latest/thiserror/) (but not necessary if you don't want to, but simplifies the creation of custom error types) instead of just providing a unit type as the error type.

2024-03-11 22:14 UTC, reaovyd commented on .github/workflows/rust.yml
> +      run: cargo test --verbose
Question: [`cargo test` already builds the binaries and libraries ](https://doc.rust-lang.org/cargo/commands/cargo-test.html) and we're not specifying which targets we want. If the purpose of the `cargo build` is to fully check compilation errors, shouldn't `cargo test` already be enough here if we're not specifying any target?

2024-03-11 22:14 UTC, reaovyd commented on .github/workflows/rust.yml
> +      run: sudo apt update && sudo apt install -y protobuf-compiler
Suggestion: I think we can add a `cargo fmt --check` check here and a `cargo clippy` step here in the CI for the self-explanatory reason that it just does format checking and common lint checks.

2024-03-11 22:14 UTC, reaovyd commented on src/main.rs
> +        (*market_data.files.entry(file_hash.clone()).or_default()).push(file_request);
Suggestion (non blocking): The `clone` here is unnecessary since you already cloned the `String` previously in which case the local variable `file_hash` is owned by the scope of the `register_file` method. E.g. you can have 
```Rust
        (*market_data.files.entry(file_hash).or_default()).push(file_request);
```
and `cargo` doesn't complain.

2024-03-11 22:14 UTC, reaovyd commented on src/main.rs
>          let mut market_data = self.market_data.lock().await;
Suggestion: you can probably just use a regular synchronous `Mutex` rather than an async Mutex. [tokio](https://docs.rs/tokio/latest/tokio/sync/struct.Mutex.html) has a good section on the reasoning there. 

But a TLDR of their reasoning is basically that if what you're locking is DB connections (or IO resources, in general), then it is recommended to use async mutices rather than sync ones. But in this case, it's only for data within the process itself in which case it is way better to use a synchronous Mutex here like from the `std` library or the one from `parking_lot`.

2024-03-22 15:20 UTC, rads284 approved these changes

2024-03-22 15:21 UTC, merged